[build]
  command = "npm ci --prefix backend && npm ci --prefix frontend && npm run build --prefix frontend"
  publish = "frontend/build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/api/:splat"
  status = 200

[[redirects]]
  from = "/uploads/*"
  to = "/.netlify/functions/api/uploads/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
